// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRcTJ0U95t3Z-PS23N0BdGR2eBPIHezA8',
    appId: '1:1081576616974:web:3134ee0ed5b6a5b69bb85f',
    messagingSenderId: '1081576616974',
    projectId: 'ween-app-2c3e2',
    authDomain: 'ween-app-2c3e2.firebaseapp.com',
    storageBucket: 'ween-app-2c3e2.appspot.com',
    measurementId: 'G-GGLRQ6BMTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9j3s8my5lezS7RJNB9BpCbjJ-B0TyoDw',
    appId: '1:1081576616974:android:4891b8344b98d7489bb85f',
    messagingSenderId: '1081576616974',
    projectId: 'ween-app-2c3e2',
    storageBucket: 'ween-app-2c3e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1dojmu46xexqWUe5GmWFcOTUceZpVnPM',
    appId: '1:1081576616974:ios:3477c29f0369eba19bb85f',
    messagingSenderId: '1081576616974',
    projectId: 'ween-app-2c3e2',
    storageBucket: 'ween-app-2c3e2.appspot.com',
    iosBundleId: 'com.example.ween',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1dojmu46xexqWUe5GmWFcOTUceZpVnPM',
    appId: '1:1081576616974:ios:a3eeff406423834d9bb85f',
    messagingSenderId: '1081576616974',
    projectId: 'ween-app-2c3e2',
    storageBucket: 'ween-app-2c3e2.appspot.com',
    iosBundleId: 'com.example.ween.RunnerTests',
  );
}
